### ISSUE TITLE
 Skipped building voxeet-sdk-ios due to the error:

### ISSUE THREAD

**Issue by shireeshMs** [voxeet/voxeet-sdk-ios-gettingstarted#1]
*** Fetching voxeet-sdk-ios
*** Checking out voxeet-sdk-ios at "v2.2.1"
*** xcodebuild output can be found in /var/folders/kv/t28f2ddd33l2n4p1701p7fjh0000gq/T/carthage-xcodebuild.Tug8PV.log
*** Skipped building voxeet-sdk-ios due to the error:
Dependency "voxeet-sdk-ios" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/voxeet/voxeet-sdk-ios/issues/new

**Comment by VTCoco** [comment]
Hi, this issue should be solved with: https://github.com/voxeet/voxeet-sdk-ios-gettingstarted/pull/2
